### ISSUE TITLE
Importing after installation doesn't work

### ISSUE THREAD

**Issue by ptsteadman** [theprate/react-iframe-resizer#1]
Hey, `npm installing` this module doesn't work because the dist directory isn't created, and `iframe-resizer` is a peer dependency.  Happy to make a PR to fix this, but wanted to make sure there wasn't a reason why things are the way they are first.

**Comment by brudil** [comment]
Sorry, I didn't whitelist the `dist` directory to npm. I had been using the js:main uncompiled files, so I hadn't noticed. Pushed & published 1.0.1.

I'm probably wrong, but shouldn't iframe-resizer be a peer dependancy?
