### ISSUE TITLE
Alternative: react-iframe-resizer-super

### ISSUE THREAD

**Issue by zeroasterisk** [theprate/react-iframe-resizer#2]
Just in case you're interested, here's an alternative I wired together, based on a (non-react) robust iframe resizing library.
https://github.com/zeroasterisk/react-iframe-resizer-super/
https://zeroasterisk.github.io/react-iframe-resizer-super/

**Comment by brudil** [comment]
This is cool! This component is just a simple react wrapper for iframe-resizer.
